apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateway-api-test
  name: svc-gateway
  namespace: gateway-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gateway-api-test
  type: CLusterIP
status:
  loadBalancer: {}
